# railway.toml
# Configuration for JANUA Financial API deployment on Railway

[build]
# Use Docker for more control over the build process
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
watchPatterns = ["backend/**"]

[deploy]
# Healthcheck ensures Railway knows if app is running correctly
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
# Set environment variables here (optional, but cleaner than in the dashboard)
APP_NAME = "JANUA Financial Analysis API"
APP_VERSION = "1.0.0"
ALLOWED_ORIGINS = "[\"https://janua.pt\",\"https://www.janua.pt\",\"http://localhost:5173\",\"http://localhost:3000\"]"
LOG_LEVEL = "INFO"
PYTHONUNBUFFERED = "1"
