# railway.toml
# Configuration for JANUA Financial API deployment on Railway

[build]
# Use Docker for more control over the build process
builder = "DOCKERFILE"
# Dockerfile path is relative to repository root (Railway uses repo root as context)
dockerfilePath = "backend/Dockerfile"
# Set build context to backend directory
dockerContext = "backend"

[deploy]
# Let Dockerfile CMD handle the start command
# Healthcheck ensures Railway knows if app is running correctly
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
# Set environment variables here
APP_NAME = "JANUA Financial Analysis API"
APP_VERSION = "1.0.0"
ALLOWED_ORIGINS = "https://janua.pt,https://www.janua.pt,http://localhost:5173,http://localhost:3000"
LOG_LEVEL = "INFO"
PYTHONUNBUFFERED = "1"
