export const createEmptyBalanceSheet = () => ({
  ativos_fixos_tangiveis: 0,
  propriedades_investimento: 0,
  goodwill: 0,
  ativos_intangiveis: 0,
  investimentos_financeiros: 0,
  acionistas_socios_nc: 0,
  outros_ativos_financeiros: 0,
  ativos_impostos_diferidos: 0,
  outros_ativos_nao_correntes: 0,
  inventarios: 0,
  clientes: 0,
  adiantamentos_fornecedores: 0,
  estado_outros_entes_publicos_ativo: 0,
  acionistas_socios_corrente: 0,
  outras_contas_receber: 0,
  diferimentos_ativo: 0,
  ativos_financeiros_correntes: 0,
  outros_ativos_correntes: 0,
  caixa_depositos_bancarios: 0,
  capital_realizado: 0,
  acoes_quotas_proprias: 0,
  outros_instrumentos_capital_proprio: 0,
  premios_emissao: 0,
  reservas_legais: 0,
  outras_reservas: 0,
  resultados_transitados: 0,
  ajustamentos_ativos_financeiros: 0,
  excedentes_revalorizacao: 0,
  outras_variacoes_capital_proprio: 0,
  resultado_liquido_periodo: 0,
  interesses_minoritarios: 0,
  provisoes_nc: 0,
  financiamentos_obtidos_nc: 0,
  responsabilidades_beneficios_pos_emprego: 0,
  passivos_impostos_diferidos: 0,
  outras_contas_pagar_nc: 0,
  outros_passivos_nao_correntes: 0,
  fornecedores: 0,
  adiantamentos_clientes: 0,
  estado_outros_entes_publicos_passivo: 0,
  acionistas_socios_passivo: 0,
  financiamentos_obtidos_corrente: 0,
  outras_contas_pagar_corrente: 0,
  diferimentos_passivo: 0,
  outros_passivos_correntes: 0,
});

export const createEmptyIncomeStatement = () => ({
  vendas_servicos_prestados: 0,
  subsidios_exploracao: 0,
  ganhos_perdas_subsidiarias: 0,
  variacao_inventarios_producao: 0,
  trabalhos_propria_entidade: 0,
  cmvmc: 0,
  fornecimentos_servicos_externos: 0,
  gastos_pessoal: 0,
  imparidade_inventarios: 0,
  imparidade_dividas_receber: 0,
  provisoes: 0,
  imparidade_investimentos_nao_depreciaveis: 0,
  aumentos_reducoes_justo_valor: 0,
  outros_rendimentos_ganhos: 0,
  outros_gastos_perdas: 0,
  gastos_depreciacoes_amortizacoes: 0,
  juros_rendimentos_obtidos: 0,
  juros_gastos_suportados: 0,
  imposto_rendimento: 0,
});

export const createEmptyCompanyInfo = () => ({
  nome_empresa: '',
  setor_atividade: '',
  objetivo_relatorio: '',
  email_empresario: '',
});

export const createEmptyFinancialData = () => ({
  nome_entidade: '',
  balanco: {
    year_n: createEmptyBalanceSheet(),
    year_n1: createEmptyBalanceSheet(),
    year_n2: createEmptyBalanceSheet(),
  },
  demonstracao_resultados: {
    year_n: createEmptyIncomeStatement(),
    year_n1: createEmptyIncomeStatement(),
    year_n2: createEmptyIncomeStatement(),
  },
});

export const createEmptyEnhancedFinancialData = () => ({
  company_info: createEmptyCompanyInfo(),
  balanco: {
    year_n: createEmptyBalanceSheet(),
    year_n1: createEmptyBalanceSheet(),
    year_n2: createEmptyBalanceSheet(),
  },
  demonstracao_resultados: {
    year_n: createEmptyIncomeStatement(),
    year_n1: createEmptyIncomeStatement(),
    year_n2: createEmptyIncomeStatement(),
  },
});
