export const balanceSheetFields = {
  'Ativo Não Corrente': [
    { key: 'ativos_fixos_tangiveis', label: 'Ativos Fixos Tangíveis' },
    { key: 'propriedades_investimento', label: 'Propriedades de Investimento' },
    { key: 'goodwill', label: 'Goodwill' },
    { key: 'ativos_intangiveis', label: 'Ativos Intangíveis' },
    { key: 'investimentos_financeiros', label: 'Investimentos Financeiros' },
    { key: 'acionistas_socios_nc', label: 'Acionistas/Sócios (NC)' },
    { key: 'outros_ativos_financeiros', label: 'Outros Ativos Financeiros' },
    { key: 'ativos_impostos_diferidos', label: 'Ativos por Impostos Diferidos' },
    { key: 'outros_ativos_nao_correntes', label: 'Outros Ativos Não Correntes' },
  ],
  'Ativo Corrente': [
    { key: 'inventarios', label: 'Inventários' },
    { key: 'clientes', label: 'Clientes' },
    { key: 'adiantamentos_fornecedores', label: 'Adiantamentos a Fornecedores' },
    { key: 'estado_outros_entes_publicos_ativo', label: 'Estado e Outros Entes Públicos' },
    { key: 'acionistas_socios_corrente', label: 'Acionistas/Sócios (Corrente)' },
    { key: 'outras_contas_receber', label: 'Outras Contas a Receber' },
    { key: 'diferimentos_ativo', label: 'Diferimentos' },
    { key: 'ativos_financeiros_correntes', label: 'Ativos Financeiros Correntes' },
    { key: 'outros_ativos_correntes', label: 'Outros Ativos Correntes' },
    { key: 'caixa_depositos_bancarios', label: 'Caixa e Depósitos Bancários' },
  ],
  'Capital Próprio': [
    { key: 'capital_realizado', label: 'Capital Realizado' },
    { key: 'acoes_quotas_proprias', label: 'Ações/Quotas Próprias' },
    { key: 'outros_instrumentos_capital_proprio', label: 'Outros Instrumentos de Capital Próprio' },
    { key: 'premios_emissao', label: 'Prémios de Emissão' },
    { key: 'reservas_legais', label: 'Reservas Legais' },
    { key: 'outras_reservas', label: 'Outras Reservas' },
    { key: 'resultados_transitados', label: 'Resultados Transitados' },
    { key: 'ajustamentos_ativos_financeiros', label: 'Ajustamentos em Ativos Financeiros' },
    { key: 'excedentes_revalorizacao', label: 'Excedentes de Revalorização' },
    { key: 'outras_variacoes_capital_proprio', label: 'Outras Variações no Capital Próprio' },
    { key: 'resultado_liquido_periodo', label: 'Resultado Líquido do Período' },
    { key: 'interesses_minoritarios', label: 'Interesses Minoritários' },
  ],
  'Passivo Não Corrente': [
    { key: 'provisoes_nc', label: 'Provisões' },
    { key: 'financiamentos_obtidos_nc', label: 'Financiamentos Obtidos' },
    { key: 'responsabilidades_beneficios_pos_emprego', label: 'Responsabilidades por Benefícios Pós-Emprego' },
    { key: 'passivos_impostos_diferidos', label: 'Passivos por Impostos Diferidos' },
    { key: 'outras_contas_pagar_nc', label: 'Outras Contas a Pagar' },
    { key: 'outros_passivos_nao_correntes', label: 'Outros Passivos Não Correntes' },
  ],
  'Passivo Corrente': [
    { key: 'fornecedores', label: 'Fornecedores' },
    { key: 'adiantamentos_clientes', label: 'Adiantamentos de Clientes' },
    { key: 'estado_outros_entes_publicos_passivo', label: 'Estado e Outros Entes Públicos' },
    { key: 'acionistas_socios_passivo', label: 'Acionistas/Sócios' },
    { key: 'financiamentos_obtidos_corrente', label: 'Financiamentos Obtidos' },
    { key: 'outras_contas_pagar_corrente', label: 'Outras Contas a Pagar' },
    { key: 'diferimentos_passivo', label: 'Diferimentos' },
    { key: 'outros_passivos_correntes', label: 'Outros Passivos Correntes' },
  ],
};

export const incomeStatementFields = {
  'Rendimentos e Ganhos': [
    { key: 'vendas_servicos_prestados', label: 'Vendas e Serviços Prestados' },
    { key: 'subsidios_exploracao', label: 'Subsídios à Exploração' },
    { key: 'ganhos_perdas_subsidiarias', label: 'Ganhos/Perdas de Subsidiárias, Assoc. e Empr. Conjuntos' },
    { key: 'variacao_inventarios_producao', label: 'Variação nos Inventários da Produção' },
    { key: 'trabalhos_propria_entidade', label: 'Trabalhos para a Própria Entidade' },
    { key: 'outros_rendimentos_ganhos', label: 'Outros Rendimentos e Ganhos' },
  ],
  'Gastos e Perdas': [
    { key: 'cmvmc', label: 'Custo das Mercadorias Vendidas e Mat. Consumidas' },
    { key: 'fornecimentos_servicos_externos', label: 'Fornecimentos e Serviços Externos' },
    { key: 'gastos_pessoal', label: 'Gastos com Pessoal' },
    { key: 'imparidade_inventarios', label: 'Imparidade de Inventários (perdas/reversões)' },
    { key: 'imparidade_dividas_receber', label: 'Imparidade de Dívidas a Receber (perdas/reversões)' },
    { key: 'provisoes', label: 'Provisões (aumentos/reduções)' },
    { key: 'imparidade_investimentos_nao_depreciaveis', label: 'Imparidade de Investimentos Não Depreciáveis (perdas/reversões)' },
    { key: 'aumentos_reducoes_justo_valor', label: 'Aumentos/Reduções de Justo Valor' },
    { key: 'outros_gastos_perdas', label: 'Outros Gastos e Perdas' },
  ],
  'Resultado antes de depreciações, gastos de financiamento e impostos': [
    { key: 'gastos_depreciacoes_amortizacoes', label: 'Gastos/Reversões de Depreciação e Amortização' },
  ],
  'Resultado operacional (antes de gastos de financiamento e impostos)': [
    { key: 'juros_rendimentos_obtidos', label: 'Juros e Rendimentos Similares Obtidos' },
    { key: 'juros_gastos_suportados', label: 'Juros e Gastos Similares Suportados' },
  ],
  'Resultado antes de impostos': [
    { key: 'imposto_rendimento', label: 'Imposto sobre o Rendimento do Período' },
  ],
};
